#ifndef _GROUPFILELOADUTIL_H
#define _GROUPFILELOADUTIL_H


// Generated by mkproto
#define RENAME_ENTRY 0
#define RENAME_DEF	 1
#define RENAME_REF	 2

void *groupRenameCreate(const char *fname);
void groupRenameFree(void *rename_void);
void groupRename(void *rename_void,const char *oldname,char *str,int typeToBeRenamed);
int groupPruneDefs(int prune_libs);
// End mkproto
#endif
