#ifndef _CONTAINEREMAIL_H
#define _CONTAINEREMAIL_H

typedef struct EmailInfo EmailInfo;

// Generated by mkproto
EmailInfo *emailAllocInfo();
void emailFreeInfo(EmailInfo *email_info);
char *emailTemplate();
char *emailSchema();
void emailSend(int sender_id, int auth_id, char *subject,char *message,int *db_ids,int count,int *container_id_ptr, int influence, char * pchAttachment );
void emailCheckNewHeaders();
void emailSendNewHeader(int db_id,char *str,int sender_id);
void emailGetHeaders(int db_id);
void emailGetMessage(int db_id,int message_id);
void emailDeleteMessage(Entity* e,int message_id);
void emailHandleSendCmd(struct Entity* e, char* subj, char* recips, char* body, int influence, int type, int idx, struct ClientLink* client);
typedef struct Packet Packet;
void createEmailFromDbServer( Packet * pak );
int emailGrantAttachment( Entity *e, char *attachment, int emailIndex);
int emailClaimItems( Entity *e, char * attachment, int emailIndex );
void createSystemEmail( Entity *e, char* senderName, char* subject, char* msg, int influence, char *attachment, int delaytime );

void checkPendingTransactions(Entity *e);

// End mkproto
#endif
