#ifndef _WIN_INIT_H
#define _WIN_INIT_H

#include "wininclude.h"
extern HINSTANCE glob_hinstance;
extern HWND	hwnd;

// Generated by mkproto
void winMakeCurrent();
void windowSize(int *width,int *height);
void windowClientSize(int *width, int *height);
int windowScaleY(int y);
void windowPosition(int *left,int *top);
void windowResize(int width,int height);
void windowInit(int *widthp,int *heightp,int fullscreen,int maximize);
void windowExit();
void windowUpdate();
void windowProcessMessages();
void windowShowError(PTSTR str);
void windowsDialog( char *str );
void winMsgAlert(PTSTR str);
int winMsgYesNo(char *str);
char *winGetFileName(char *fileMask,char *fileName,int save);
int winMaximized();
void winSetText(char *s);
void winCopyToClipboard(const char* s);
// End mkproto

char* winGetString(char* prompt, char* result); 
	// prompt for a string with a windows dialog box, returns NULL on cancel

#endif
