#ifndef _SVR_TICK_H
#define _SVR_TICK_H

#define DAY_TIMESCALE 48.f // times faster than a normal day
extern int server_error_sent_count;

typedef struct Packet Packet;
typedef struct NetLink NetLink;

// Generated by mkproto
int svrHandleClientMsg(Packet *pak, int cmd, NetLink *link);
void svrTick();
void svrTimeSet(F32 time);

void logDisconnect(ClientLink *client, const char * reason);

U32		svrGetSecondsIdle(void);
void	svrResetSecondsIdle(void);

// End mkproto
#endif
