#ifndef _GRIDCOLLPERFTEST_H
#define _GRIDCOLLPERFTEST_H

#if 0 || CLIENT
#define saveCollRec(start,end,radius,flags,got_hit,hit_pos)
#else
#define saveCollRec(start,end,radius,flags,got_hit,hit_pos) saveCollRecX(start,end,radius,flags,got_hit,hit_pos)
#endif

// Generated by mkproto
void saveCollRecX(const Vec3 start,const Vec3 end,F32 radius, U32 flags, int got_hit, const Vec3 hit_pos);
void loadCollRec();
void coll_err(int pos_err);
void quantizeVec3(Vec3 v);
void runCollRec();
void testColl();
void gridCollPerfTest();
void gridCollRecordStart();
void gridCollRecordStop();
// End mkproto
#endif
