#ifndef _GRIDCOLLOBJ_H
#define _GRIDCOLLOBJ_H

#define XLO 0x55
#define YLO 0x0f
#define ZLO 0x33



// Generated by mkproto
int checkTriColl(Model *model,int idx,CollInfo *coll,Vec3 obj_start,Vec3 obj_end,DefTracker *node);
int checkTriCacheColl(CollInfo *coll);
int collObj(DefTracker *node,const Vec3 start,CollInfo *coll);
void setTriCollState(CollInfo *coll);
int collGridObj(DefTracker *tracker,const Vec3 start,const Vec3 end,CollInfo *coll);
// End mkproto
#endif
