#ifndef _GRIDFIND_H
#define _GRIDFIND_H

#include "stdtypes.h"

typedef struct Grid Grid;
typedef struct GridCell GridCell;

typedef int GridEntryCallback(void *);

// Generated by mkproto
void gridFindObjectsInSphereCB(Grid *grid,GridEntryCallback *callback,Vec3 point,F32 radius);
int gridFindObjectsInSphere(Grid *grid,void **list,int max_count,const Vec3 point,F32 radius);
GridCell *gridFindCell(Grid *grid,Vec3 pos,void **obj_list,int *count_ptr,int max_count);
// End mkproto
#endif
