typedef enum {
	FLOOD_TCPCONNECT,
	FLOOD_TCPLARGE,
	FLOOD_TCPSMALL,
	FLOOD_TCPGARBAGE,
	FLOOD_TCPCHECKSUMMED,
	FLOOD_TCPSTREAM,
	FLOOD_UDPLARGE,
	FLOOD_UDPSMALL,
	FLOOD_UDPGARBAGE,
	FLOOD_UDPCHECKSUMMED,
	FLOOD_UDPSTREAM,
} FloodMode;

void packetFlood(char *dest, int port, FloodMode mode, int num);