#ifndef _CLIENTENTITYLINK_H
#define	_CLIENTENTITYLINK_H

#include "wininclude.h"

typedef struct Entity Entity;
typedef struct ClientLink ClientLink;

// Generated by mkproto
void clientSetEntity(ClientLink* client, Entity* ent);
void clientSetSlave(ClientLink* client, Entity* ent, int control);
Entity* clientGetViewedEntity(ClientLink* client);
Entity* clientGetControlledEntity(ClientLink* client);
int clientIsSlave(ClientLink* client);
Entity* clientGetSlave(ClientLink* client);
ClientLink* clientGetMaster(ClientLink* client);
void freePlayerControl( ClientLink* client );
void getPlayerControl( ClientLink* client, int control );
// End mkproto
#endif
