##############################################################################
# Name: Makefile
#

TOP     = ../..
HERE    = arda2/error

##############################################################################
# Define all local variables after the following line.
include $(TOP)/configure.mk

SRCS_CPP = errErrorHandlerLogger.cpp

LIBNAME = ArdaError

##############################################################################
# Define all local rules after the following line.
include $(CONFIG_DIR)/rules.mk

