//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resources.rc
//
#define IDCANCEL                        2
#define IDI_ICON1                       101
#define IDD_DLGMAIN                     103
#define IDD_DLGTEXTMAIN                 105
#define IDD_DLGTEXTTAB                  106
#define IDC_LIST2                       1005
#define IDEXIT                          1006
#define IDC_LOG                         1007
#define IDCHECK_STATUS                  1008
#define IDKILLALL                       1009
#define IDC_COMBO1                      1010
#define IDKILL                          1010
#define IDC_FULL_COMMAND                1010
#define IDLAUNCH                        1011
#define IDLOGOUT                        1012
#define IDSHOW                          1015
#define IDHIDE                          1016
#define IDC_RADIO1                      1019
#define IDC_RADIO2                      1020
#define IDC_PARAMS                      1021
#define IDC_CHK_HIDE                    1022
#define IDC_CHK_JUSTLOGIN               1023
#define IDC_CHK_DISCONNCT               1024
#define IDC_CHK_MAPMOVE                 1025
#define IDC_CHECK1                      1026
#define IDC_CHK_MOVE                    1026
#define IDC_TOGGLE_TEAM                 1026
#define IDC_CS                          1027
#define IDC_TOGGLE_TEAM2                1027
#define IDC_TOGGLE_AUTOREPLY            1027
#define IDC_EDIT1                       1028
#define IDC_COMMANDEDIT                 1028
#define IDC_BATCHFILE                   1028
#define IDC_CHK_LMS                     1029
#define IDC_BATCHFILE2                  1029
#define IDC_LOGFILE                     1029
#define IDC_HELPBTN                     1030
#define IDC_CHK_TIMED_RECONNECT         1031
#define IDC_CHK_RANDOM_DISCONNECT       1032
#define IDC_CHK_AUTHSERVER              1033
#define IDC_CHK_ASK_USER                1034
#define IDC_CHK_NOTIMEOUT               1035
#define IDC_CHK_FIGHT                   1036
#define IDC_CHK_FIGHT2                  1037
#define IDC_CHK_AUTOREZ                 1037
#define IDC_CHECK2                      1038
#define IDC_CHK_MISSIONS                1038
#define IDC_TOGGLE_SG                   1038
#define IDC_LIST1                       1039
#define IDC_BTN_SETNEXT                 1040
#define IDC_ALIGNME                     1041
#define IDC_UPPERLEFT                   1042
#define IDC_BTN_CONSOLE                 1043
#define IDC_CHK_TEAMUP                  1044
#define IDC_CHECK3                      1045
#define IDC_CHK_SILENT                  1045
#define IDC_PAUSEBATCH                  1045
#define IDSENDCOMMAND                   1046
#define IDC_AUTHNAME                    1047
#define IDC_CHK_LMS2                    1048
#define IDC_CHK_NOPARSECHAT             1048
#define IDC_CHK_NOLAUNCHERCHAT          1048
#define IDC_CHK_ARENAFIGHTER            1049
#define IDC_PASSWORD                    1050
#define IDC_QUICK_COMMAND               1050
#define IDC_CHARACTER                   1051
#define IDC_QUICK_TARGET                1051
#define IDC_CHK_KILLBOT                 1052
#define IDC_CHK_EVENTCREATOR            1053
#define IDC_EDIT_AUTHNAME               1054
#define IDC_CHK_COV                     1054
#define IDC_EDIT_PASSWORD               1055
#define IDC_CHK_ARENATHRASHER           1055
#define IDC_EDIT_CHARACTER              1056
#define IDC_CHK_ARENASUPERGROUP         1056
#define IDC_LOGIN                       1057
#define IDC_CHK_CHAT                    1057
#define IDC_LOGINGROUP                  1058
#define IDC_CHK_AUTHSERVER2             1058
#define IDC_CHK_PACKETDEBUG             1058
#define IDC_LOGINGROUP2                 1059
#define IDC_CHK_MISSION_STRESS          1059
#define IDC_GB_QUICKCOMMAND             1060
#define IDC_CHK_MAPMOVE_STRESS          1060
#define IDC_CLIENT_UPDATE               1061
#define IDC_CHK_INFOBOX                 1061
#define IDC_CHK_VERBOSE                 1061
#define IDC_EDIT_AUTOREPLY              1062
#define IDC_STATUS_BOX                  1063
#define IDC_SEND_COMMAND                1064
#define IDC_MAPNAME                     1065
#define IDC_HITPOINTS                   1066
#define IDC_RUNBATCH                    1067
#define IDC_EDIT_VERSION                1068
#define IDC_LOCKCHAT                    1069
#define IDC_EDIT_EXTRA_ARGS             1069
#define IDC_TEXT_OUTPUT2                1070
#define IDC_EDIT_LAUNCH_DELAY           1070
#define IDC_COPY                        1071
#define IDC_USER0                       1072
#define IDC_USER1                       1073
#define IDC_USER2                       1074
#define IDC_USER3                       1075
#define IDC_USER4                       1076
#define IDC_USER5                       1077
#define IDC_CONSOLE                     1078
#define IDC_CLEAR                       1079
#define IDC_LAUNCHCOUNT                 1079
#define IDC_EDIT_LAUNCH_COUNT           1079
#define IDC_CHK_ARENASCHEDULED          1080
#define IDC_CONSOLE2                    1080
#define IDC_COV                         1080
#define IDC_LOGCHAT                     1081
#define IDC_CHK_ACCOUNTSERVER           1081
#define IDC_CHK_ACCOUNTSERVER2          1082
#define IDC_CHK_INCREMENTAUTH           1082
#define IDC_CHK_AUCTION                 1083
#define IDC_CHK_AUCTIONSERVER           1083
#define IDC_CHK_LEAGUE                  1084
#define IDC_CHK_NOSHAREDMEM             1085
#define IDC_CHK_TURNSTILE				1086
#define IDLOGALLOUT                     1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
