#ifndef _MODEL_H
#define _MODEL_H

#include "stdtypes.h"
#include "rt_state.h"

typedef struct TrickNode TrickNode;
typedef struct TexBind TexBind;
typedef struct GeoLoadData GeoLoadData;
typedef struct PackNames PackNames;
typedef struct Model Model;


//Editing tool, don't know why it's in model.h
typedef struct Line
{
	Vec3	a,b;
	U8		color[4];
	F32		width;
} Line;

// Generated by mkproto
TrickNode *allocModelTrick(Model *model);
void validateAllTextures( GeoLoadData * gld, TexBind **binds, PackNames * texnames );
void addModelData(GeoLoadData * gld);
void addModelDataSingle(Model *model);
U32 texNeedsAlphaSort(TexBind *bind, BlendModeType blend);
U32 modelNeedsAlphaSort(Model *model);
void modelResetFlags(Model *model); // Used by modelResetAllFlags on reload
void modelResetVBOs(bool freeModels);
// End mkproto
#endif
