#ifndef _ENTWORLDCOLL_H
#define _ENTWORLDCOLL_H

#include "stdtypes.h"

extern int coll_is_player;
extern int landed_on_ground;

typedef struct SurfaceParams SurfaceParams;
typedef struct Entity Entity;

// Generated by mkproto
F32 HeightAtLoc(const Vec3 vec, F32 radius, F32 dist);
F32 entHeight(Entity *e,F32 dist);
void entWorldCollide(Entity* e, const Mat3 control_mat);
void entWorldGetSurface(Entity *e,SurfaceParams *surf);
SurfaceParams *entWorldGetSurfaceModifier(Entity *e);
void entWorldApplySurfMods(SurfaceParams *surf_mod,SurfaceParams *surf);
void entWorldApplyTextureOverrides( SurfaceParams *	surf, int lastSurfFlags );
// End mkproto
#endif
