#ifndef _GRIDPOLY_H
#define _GRIDPOLY_H

#ifdef __cplusplus
	extern "C" {
#endif

typedef struct GMesh GMesh;

typedef struct PolyCell
{
	struct PolyCell **children;
	U16		*tri_idxs;
	int		tri_count;
} PolyCell;

typedef struct
{
	PolyCell	*cell;
	Vec3		pos;
	F32			size;
	F32			inv_size;
	int			tag;
	int			num_bits;
} PolyGrid;

// Generated by mkproto
int bitnum(F32 size);
void pstats(PolyCell *cell,int depth);
F32 powSnapCeil(F32 val,F32 pow);
void powCubeSnap(Vec3 v,F32 pow);
void gridPolys(PolyGrid *grid,GMesh *mesh);
PolyCell *polyGridFindCell(PolyGrid *grid,Vec3 pos,F32 *size_ptr);
int *polyGridFindTris(PolyGrid *grid, Vec3 min, Vec3 max, int *tricount_ptr);
void polyGridFree(PolyGrid *grid);
void writePolyGridDebugFile(PolyGrid *grid, char *fname);
// End mkproto

#ifdef __cplusplus
	}
#endif

#endif
