#ifndef _CONSOLE_H
#define _CONSOLE_H

#include "uiInclude.h"

typedef struct MRUList MRUList;

// Generated by mkproto
void conCreate(void);
void conPrint(char *s);
void conPrintf(char const *fmt, ...);
void conPrintfUpdate(char const *fmt, ...);
void conPrintfVerbose(char const *fmt, ...);
void conRender(void);
void conGetInput(void);
void conProcess(void);
int conVisible(void);
MRUList *conGetMRUList(void);
// End mkproto

#endif
