##############################################################################
# Name: Makefile
#

TOP     = ../..
HERE    = arda2/math

##############################################################################
# Define all local variables after the following line.
include $(TOP)/configure.mk


LIBNAME = ArdaMath



SRCS_CPP = 	matConstants.cpp matFarPosition.cpp matRandom.cpp 	\
		matTransform.cpp matFarTransform.cpp matVector3.cpp 	\
		matVector4.cpp matQuaternion.cpp matD3DXMathEmu.cpp 	\
		matPlane.cpp matIntersect.cpp matMatrix4x4.cpp 		\
		matDistance.cpp matProperty.cpp matAdapters.cpp 	\
		matColor.cpp matUtils.cpp

##############################################################################
# Define all local rules after the following line.
include $(CONFIG_DIR)/rules.mk

