//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ServerMonitor.rc
//
#define IDD_DLG_SVRMON                  101
#define IDD_DLG_ENTS                    102
#define IDI_ICON1                       103
#define IDD_PROMPT                      104
#define IDD_DLG_STATUS                  105
#define IDD_DLG_CMDRELAY                106
#define IDD_DLG_SHARDMON                107
#define IDD_DLG_SHARDMON_CONFIGURE      108
#define IDD_DLG_NEWSHARD                110
#define IDI_ICON2                       112
#define IDD_DIALOG1                     113
#define IDD_DLG_MAIN                    113
#define IDD_DLG_PROCESSMON              115
#define IDD_DLG_CHATMON                 116
#define IDD_DIALOG2                     117
#define IDD_DLG_UPDATESERVERS           117
#define IDD_DLG_OVERLOADPROTECTION      118
#define IDC_LST_LAUNCHERS               1001
#define IDC_LST_MS                      1002
#define IDC_LST_MS_STUCK                1003
#define IDC_BTN_MSSHOW                  1004
#define IDC_BTN_MSHIDE                  1005
#define IDC_BTN_MSDELINK                1006
#define IDC_BTN_MSVIEWENTS              1007
#define IDC_BTN_SMSSHOW                 1008
#define IDC_BTN_SMSHIDE                 1009
#define IDC_BTN_SMSDELINK               1010
#define IDC_BTN_SMSREMOTEDEBUG          1011
#define IDC_BTN_SMSDELINK2              1012
#define IDC_BTN_SMSVIEWERROR            1012
#define IDC_BTN_CONNECT                 1013
#define IDC_BTN_KILLPROCESS             1014
#define IDC_BTN_SMSKILL                 1014
#define IDC_BTN_CONNECT_SINGLE          1014
#define IDC_BTN_SHUTDOWNALL             1015
#define IDC_BTN_VIEWENTS                1016
#define IDC_TXT_MSCOUNT                 1017
#define IDC_TXT_LCOUNT                  1018
#define IDC_TXT_PCOUNT                  1019
#define IDC_TXT_ECOUNT                  1020
#define IDC_BTN_REQUEST                 1021
#define IDC_TXT_PCOUNT_HERO             1021
#define IDC_TXT_MCOUNT                  1022
#define IDC_BTN_REQUESTDIFF             1023
#define IDC_TXT_PCOUNT_VILLAIN          1023
#define IDC_TXT_PCOUNTCON               1024
#define IDC_LST_ENTS                    1025
#define IDC_TXT_PCOUNTENTS              1025
#define IDC_TXT_LOGINCOUNT              1026
#define IDC_TXT_DBSERVER                1027
#define IDC_TXT_SERVERVER               1028
#define IDC_TXT_GAMEVER                 1029
#define IDC_BTN_MEMDUMP                 1030
#define IDC_BTN_SAKILL                  1030
#define IDC_UPPERLEFT                   1031
#define IDC_ALIGNME                     1032
#define IDC_CHK_AUTODELINK              1033
#define IDC_TXT_AUTODELINKTIME          1034
#define IDC_BTN_FAKETROUBLE             1035
#define IDC_TXT_QUEUEDCOUNT             1035
#define IDC_VALUE                       1036
#define IDC_TXT_SQLWB                   1036
#define IDC_NAME                        1037
#define IDC_BTN_SMSRDC                  1037
#define IDC_BTN_MSRDC                   1038
#define IDC_BTN_MSRDC2                  1039
#define IDC_BTN_LRDC                    1039
#define IDC_EDIT_CRASH_MSG              1040
#define IDC_LST_MS_STUCK2               1040
#define IDC_LST_SERVERAPPS              1040
#define IDC_BTN_SARDC                   1041
#define IDC_TXT_SQLFOREIDLERATIO        1042
#define IDC_TXT_LOGLAT                  1043
#define IDC_BUTTON_STATUS_COPY          1043
#define IDC_BUTTON1                     1044
#define IDC_RELAY_APPLY_PATCH           1044
#define IDC_BTN_CONFIGURE               1044
#define IDC_BTN_ADD                     1044
#define IDC_BTN_REFRESH                 1044
#define IDC_TXT_SQLLAT                  1044
#define IDC_TXT_SQLAVGLAT               1044
#define IDC_BTN_ADMINMESSAGE            1045
#define IDC_RELAY_START_LAUNCHER        1046
#define IDC_TXT_SQLWORSTLAT             1046
#define IDC_LST_RELAY_CLIENTS           1047
#define IDC_TXT_SQLTHROUGH              1047
#define IDC_RELAY_KILLALL_LAUNCHER      1048
#define IDC_TXT_LOGQMAX                 1048
#define IDC_TXT_LOGSORTMEM              1049
#define IDC_TXT_LOGQCNT                 1050
#define IDC_TXT_LOGSORTCAP              1051
#define IDC_TXT_QUEUECONNS              1052
#define IDC_RELAY_UPDATE_SELF           1053
#define IDC_TXT_LOGBYTES                1053
#define IDC_TXT_SQLBACKIDLERATIO        1054
#define IDC_BUTTON_RELAY_CANCEL_ALL     1054
#define IDC_RELAY_START_DBSERVER        1055
#define IDC_COMBO_RELAY_UPDATE_SVR      1056
#define IDC_COMBO_RELAY_CUSTOM_CMD      1058
#define IDC_BUTTON_RELAY_CUSTOM_CMD_ALL 1059
#define IDC_BUTTON_RELAY_CUSTOM_CMD_SELECTED 1060
#define IDC_BUTTON_RELAY_CUSTOM_CMD_EXECUTE 1060
#define IDC_BTN_SENDALL                 1060
#define IDC_BUTTON_RELAY_CUSTOM_CMD_DELETE 1061
#define IDC_BTN_SENDALL2                1061
#define IDC_BTN_CHATSVR_SHUTDOWN        1061
#define IDC_BUTTON2                     1062
#define IDC_RELAY_KILLALL_MAPSERVER     1062
#define IDC_BTN_EDIT                    1062
#define IDC_BTN_SERVERMONITOR           1062
#define IDC_BTN_LIVEUPDATES             1062
#define IDC_CHAT_ADD                    1062
#define IDC_STATIC_PCOUNTENTS           1063
#define IDC_BTN_REMOVE                  1064
#define IDC_RELAY_KILLALL_BEACONIZER    1064
#define IDC_BTN_MOVEUP                  1065
#define IDC_BTN_MOVEDOWN                1066
#define IDC_LST_SHARDS                  1067
#define IDC_IPADDRESS1                  1069
#define IDC_IP                          1069
#define IDC_TXT_MAXCPU                  1070
#define IDC_TXT_MAXCPU60                1071
#define IDC_TXT_AVGCPU                  1072
#define IDC_TXT_AVGCPU60                1073
#define IDC_TXT_MINPHYS                 1074
#define IDC_TXT_MINVIRT                 1075
#define IDC_CHK_LOG                     1076
#define IDC_TXT_LOGINTERVAL             1077
#define IDC_RELAY_SELECT_ALL            1078
#define IDC_BUTTON4                     1079
#define IDC_RELAY_SELECT_NONE           1079
#define IDC_LIST1                       1079
#define IDC_LST_SHARDS1                 1079
#define IDC_TXT_MAXSECS                 1079
#define IDC_LST_SHARDS2                 1080
#define IDC_BTN_DISCONNECT              1081
#define IDC_TXT_ARENASECS               1081
#define IDC_LST_SHARDS_SUM1             1082
#define IDC_TXT_STATSECS                1082
#define IDC_BTN_DISCONNECT_SINGLE       1082
#define IDC_TAB_MAIN                    1083
#define IDC_LST_SHARDS_SUM2             1083
#define IDC_TXT_HEROAUCTIONSECS         1083
#define IDC_RELAY_UPPERLEFT             1084
#define IDC_TXT_VILLAINAUCTIONSECS      1084
#define IDC_RELAY_ALIGNME               1085
#define IDC_RELAY_RUN_BATCH_FILE        1086
#define IDC_RELAY_CONNECTED_RELAY_COUNT 1087
#define IDC_RELAY_CONNECTED_COUNT       1087
#define IDC_BTN_REMOTEDESKTOP           1088
#define IDC_LST_SERVERS                 1089
#define IDC_STATIC_CONNECTED_RELAYS     1090
#define IDC_TXT_EXENAME0                1091
#define IDC_CHK_MONITOR0                1092
#define IDC_CHK_START0                  1093
#define IDC_CHK_RESTART0                1094
#define IDC_TXT_SECONDS0                1095
#define IDC_TXT_STATUS0                 1097
#define IDC_TXT_CMDLINE0                1098
#define IDC_BUTTON3                     1099
#define IDC_CHAT_REMOVE                 1099
#define IDC_RELAY_STOP_ALL              1099
#define IDC_BTN_OVERLOADPROTECTION_ON   1099
#define IDC_LST_CHATSERVERS             1100
#define IDC_RELAY_START_ALL             1101
#define IDC_LST_CHATSHARDS              1101
#define IDC_TXT_CHATSERVER              1104
#define ID_BTN_CHATCONNECT              1105
#define IDC_BTN_CHATCONNECT             1105
#define IDC_TXT_CONNECTED_CHAT_SHARDS   1106
#define IDC_CHK_MONITOR1                1109
#define IDC_CHK_START1                  1110
#define IDC_STATIC_AUTODELINK           1110
#define IDC_CHK_RESTART1                1111
#define IDC_TXT_STUCK_TITLE             1111
#define IDC_TXT_TITLE_SMS               1111
#define IDC_TXT_SECONDS1                1112
#define IDC_TXT_TITLE_LAUNCHERS         1112
#define IDC_TXT_EXENAME1                1113
#define IDC_TXT_TITLE_MS                1113
#define IDC_TXT_STATUS1                 1114
#define IDC_TXT_TITLE_SERVERAPPS        1114
#define IDC_TXT_CMDLINE1                1115
#define IDC_CHK_LONG_TICK               1115
#define IDC_CHK_MONITOR2                1116
#define IDC_CHECK2                      1116
#define IDC_CHK_CRASHED_SERVERAPPS      1116
#define IDC_CHK_START2                  1117
#define IDC_CHK_RESTART2                1118
#define IDC_CHK_AUTOSHUTDOWN            1118
#define IDC_TXT_SECONDS2                1119
#define IDC_EDIT_OVERLOAD_MSG           1119
#define IDC_TXT_EXENAME2                1120
#define IDC_BTN_OVERLOADPROTECTION_OFF  1120
#define IDC_TXT_STATUS2                 1121
#define IDC_TXT_CMDLINE2                1122
#define IDC_CHK_MONITOR3                1123
#define IDC_CHK_START3                  1124
#define IDC_CHK_RESTART3                1125
#define IDC_TXT_SECONDS3                1126
#define IDC_TXT_EXENAME3                1127
#define IDC_TXT_STATUS3                 1128
#define IDC_TXT_CMDLINE3                1129
#define IDC_CHK_MONITOR4                1137
#define IDC_CHK_START4                  1138
#define IDC_CHK_RESTART4                1139
#define IDC_TXT_SECONDS4                1140
#define IDC_TXT_EXENAME4                1141
#define IDC_TXT_STATUS4                 1142
#define IDC_TXT_CMDLINE4                1143
#define IDC_CHK_MONITOR5                1144
#define IDC_CHK_START5                  1145
#define IDC_CHK_RESTART5                1146
#define IDC_TXT_SECONDS5                1147
#define IDC_TXT_EXENAME5                1148
#define IDC_TXT_STATUS5                 1149
#define IDC_TXT_CMDLINE5                1150
#define IDC_CHK_MONITOR6                1158
#define IDC_CHK_START6                  1159
#define IDC_CHK_RESTART6                1160
#define IDC_TXT_SECONDS6                1161
#define IDC_TXT_EXENAME6                1162
#define IDC_TXT_STATUS6                 1163
#define IDC_TXT_CMDLINE6                1164
#define IDC_TXT_BEACONWAIT              1167
#define IDC_TXT_ACCOUNTSECS             1168
#define IDC_TXT_MISSIONSECS             1169
#define IDC_BTN_RESETMISSION            1170
#define IDC_BTN_RECONCILE_LAUNCHER      1171
#define IDC_TXT_TURNSTILESECS           1172
#define IDC_TXT_OVERLOADPROTECTION      1173
#define IDC_BTN_OVERLOADPROTECTION      1174
#define IDC_BTN_LN_SUSPEND              1175
#define IDC_BTN_LN_RESUME               1176
#define IDC_TXT_MAPSTARTREQUEST_COUNT   1177
#define IDC_TXT_MAPSTARTREQUEST_RATE    1178
#define IDC_TXT_ENT_WAITING_PEAK        1179
#define IDC_TXT_TURNSTILESECS2          1179

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1500
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
