#pragma once

#include <winsock2.h>
#include <windows.h>
#include "textparser.h"

LRESULT CALLBACK DlgShardMonProc (HWND hDlg, UINT iMsg, WPARAM wParam, LPARAM lParam);

#define COLOR_TROUBLE LISTVIEW_DEFAULT_COLOR, RGB(255,180,180)
#define COLOR_TROUBLE_LIGHT LISTVIEW_DEFAULT_COLOR, RGB(255,255,180)
#define COLOR_RECONNECT LISTVIEW_DEFAULT_COLOR, RGB(180,180,255)
#define COLOR_DISABLED LISTVIEW_DEFAULT_COLOR, RGB(188,188,188)
#define COLOR_CONNECTED LISTVIEW_DEFAULT_COLOR, LISTVIEW_DEFAULT_COLOR
#define COLOR_STATS LISTVIEW_DEFAULT_COLOR, RGB(180,200,255)
//#define COLOR_DIVIDER RGB(0,0,0), RGB(0,0,0)
#define COLOR_DIVIDER RGB(255,255,255), RGB(255,255,255)
#define COLOR_BAD_VERSION LISTVIEW_DEFAULT_COLOR, LISTVIEW_BAD_VERSION_COLOR
