#ifndef _OUTPUTANIM_H
#define _OUTPUTANIM_H

#include "tree.h"
#include "animtrack.h"

enum
{
  MEM_ANIMDATA,
  MEM_BONEANIMTRACKS,
};

void *allocBlockMem(int block_num,int amount);

// Generated by mkproto
void outputGroupInfo(char *fname);
void outputResetVars(void);
void outputPackSkeletonAnimTrack( SkeletonAnimTrack * skeleton, Node *root );
void outputAnimTrackToAnimFile( SkeletonAnimTrack * skeleton, char * targetFilePath );
// End mkproto

#endif
