#ifndef _PROCESSANIM_H
#define _PROCESSANIM_H

#include "tree.h"
#include "animtrack.h"

//mm 
#define MAX_TRIIDX  3000
#define MAX_BUFFER  300000
#define MAX_TRISETS 500

#define OBJECT_LIBRARY 0
#define PLAYER_LIBRARY 1
#define ANIMATION_FILE 2

#define NO_MERGE_NODES  0
#define MERGE_NODES		1

#define PROCESS_ALL_NODES	0
#define PROCESS_GEO_ONLY	1	//process only "GEO_" prefixed geometry parts
#define PROCESS_ANIM_ONLY	2	//ignore all "GEO_" prefixed parts

#define NOT_BASE_SKELETON	0
#define IS_BASE_SKELETON	1


#define DONT_POOL_VERTS 0
#define POOL_VERTS		1

// Generated by mkproto
void orientPos(Vec3 v);
void orientAngle(Vec4 v);
Node * animConvertVrmlFileToAnimTrack( char * sourcepath, SkeletonHeirarchy * skeletonHeirarchy );
// End mkproto
#endif
