##############################################################################
# Name: Makefile
#

TOP     = ../..
HERE    = arda2/properties

##############################################################################
# Define all local variables after the following line.
include $(TOP)/configure.mk

LIBNAME = ArdaProp
SRCS_CPP = proAdapter.cpp         \
           proClass.cpp           \
           proClassAdapter.cpp    \
           proClassNative.cpp     \
           proClassOwner.cpp      \
           proClassRegistry.cpp   \
           proFirst.cpp           \
           proObject.cpp          \
           proObjectImpl.cpp      \
           proObjectReaderXML.cpp \
           proObjectWriterXML.cpp \
           proObserver.cpp        \
           proProperty.cpp        \
           proPropertyNative.cpp  \
           proPropertyOwner.cpp   \
           proStringUtils.cpp     \
           proXmlParser.cpp       \
	   proChildSort.cpp

##############################################################################
# Define all local rules after the following line.
include $(CONFIG_DIR)/rules.mk

