#ifndef CHATDEFS_H
#define CHATDEFS_H

#define MAX_CHANMOTD 5
#define MAX_STOREDMSG 10
#define MAX_GFRIENDS 200
#define MAX_IGNORES 100
#define MAX_WATCHING 15
#define MAX_MEMBERS 2500
#define MAX_INVITES	5
#define MAX_GMAIL	100
#define MAX_GMAIL_SUBJECT 80
#define MAX_GMAIL_BODY 3900

#define MAX_PLAYERNAME 21
#define MAX_CHANNELNAME 21
#define MAX_CHANNELDESC 127
#define MAX_MESSAGE 1000
#define MAX_FRIENDSTATUS 200
#define MAX_SUBJECT 80


#endif CHATDEFS_H
