#define MAX_EVER_SOUND_SPHERES	64	// can never have more than this.  actual limit is game_state.maxSoundSpheres

// sound owner id's:
enum
{
	SOUND_FX_BASE = 1000,
	SOUND_FX_LAST = 90000,
	SOUND_ZOWIE_BASE = SOUND_FX_LAST,
	SOUND_MUSIC = 100000,
	SOUND_GAME,
	SOUND_PLAYER,
	SOUND_VOICEOVER,
	SOUND_AMBIENT,
	SOUND_AMBIENT_SPHERE_BASE = SOUND_AMBIENT,
	SOUND_AMBIENT_SCRIPT_BASE = SOUND_AMBIENT_SPHERE_BASE + MAX_EVER_SOUND_SPHERES,
	SOUND_UI_REPEATING,
	SOUND_UI_REPEATING_SCROLL,
	SOUND_UI_ALTERNATE,
};
