##############################################################################
# Name: Makefile
#

TOP     = ../..
HERE    = arda2/timer

##############################################################################
# Define all local variables after the following line.
include $(TOP)/configure.mk

LIBNAME = ArdaTimer

##############################################################################
# Define all local rules after the following line.
include $(CONFIG_DIR)/rules.mk

