#ifndef _EDIT_ERRCHECK
#define _EDIT_ERRCHECK

#define WARN_LOW 0
#define WARN_HIGH 1
#define WARN_CHECKPARENT 2
#define WARN_CHECKATTACH 4
#define WARN_OFF 8

// Generated by mkproto
int selIsCubemap(void);
int selIsLights(int checkall);
int selIsSounds(int checkall);
int selIsFog(int checkall);
int selIsBeacon();
int isRootGeo(DefTracker *tracker);
int isNonLibSelectSub(int warnlevel);
void editResetCmdChecker();
int isNonLibSelect(int *memp,int warnlevel);
int isNonRootGeoSelect();
int isNonLibSingleSelect(int *memp,int warnlevel);
// End mkproto
#endif
