#ifndef _EDIT_DRAWLINES_H
#define _EDIT_DRAWLINES_H

#include "stdtypes.h"
typedef struct Line Line;

// Generated by mkproto
void add3dCursor(const Vec3 pos,const Mat3 orient_mat);
void drawRotationGuide(const Vec3 pos,const Mat3 orient_mat,int axis);
void drawLasso(int ulx,int uly,int llx,int lly);
void drawSphere(const Mat4 mat,F32 rad,int nsegs,U32 color);
void drawSphereMidRad(const Vec3 mid,F32 rad,int nsegs,U32 color);
void setLineInfo(Line *line,int gridsize,int idx,int style);
void showGrid(const Mat4 matx,int *edit_axisp,int *edit_axis,int style);
void showGrid2(const Mat4 matx,int *edit_axisp,int *edit_axis);
void editDrawSoundSpheres(void);
void editProfiler(void);
void showGridExternal(void);
// End mkproto
#endif
