#ifndef _EDIT_MISC_H
#define _EDIT_MISC_H

#include "Menu.h"

// Generated by mkproto
void editCmdSaveFile(void);
void editCmdClientSave();
void editCmdAutosave(MenuEntry *,void *);
void editCmdSceneFile(void);
void editCmdLoadScreen(void);
void editCmdExportToVrml(void);
//void editCmdCheckin(void);
void editShowTitle(void);
// End mkproto
#endif
