#ifndef _EDIT_CMD_GROUP_H
#define _EDIT_CMD_GROUP_H

#include "group.h"

// Generated by mkproto
void editCmdUngroup();
void editCmdGroup();
void editCmdAttach();
void editCmdDetach();
void editCmdOpen();
void editCmdClose();
void editCmdMouseWheelOpenClose();
void editCmdUngroupAll();
void editCmdGroupAll();
void editCmdTraySwap();
void editCmdSetFxName();
void editNameDef(GroupDef *def,char *namep);
void editName();
void editNameNewLibraryPiece();
void editCmdSetParent();
void editCmdSetActiveLayer();
void editCmdUnsetActiveLayer();

// End mkproto
#endif
