#ifndef _EDIT_INFO
#define _EDIT_INFO

#include "stdtypes.h"
#include "model.h"
#include "group.h"

typedef struct
{
	Vec3	cursor_pos;
	char	axis[10];
	char	snap[20];
	char	posrot[10];
	char	gridsize[10];
	char	rotsize[10];
	char	geo[1000];
	char	group[1000];
	int		poly_recount,last_polycount,last_objcount,last_totalgroups;
} EditStats;

extern EditStats edit_stats;


// Generated by mkproto
void showDefInfo(int xpos,int ypos,GroupDef *def);
void showTrackerInfo(int xpos,int ypos,DefTracker *tracker);
void selShow();
void printEditStats();
void printDef(GroupDef *def,int xoff);
TexBind *getTexWithReplaces(DefTracker *tracker, int idx);
const char *getTexNameWithReplaces(DefTracker *tracker, int idx);
// End mkproto
#endif
