#ifndef _EDIT_GETVALUE_H
#define _EDIT_GETVALUE_H

#include "stdtypes.h"

void getPickedColor(Vec3 rgbOut);
void edit_colorPicker_close(void);

// Generated by mkproto
void pickColorAbort();
int pickColor(int *color,int alpha);
int get2Color(int idx,int is_tint,int *memp);
// End mkproto
#endif
