#ifndef _CONTAINER_FLATFILE_H
#define _CONTAINER_FLATFILE_H


// Generated by mkproto
int containerListLoad(DbList *list,char *mem,int *idxs);
int containerListLoadFile(DbList *list);
int containerListSave(DbList *list);
// End mkproto
#endif
