#ifndef _DBMSG_H
#define _DBMSG_H


// Generated by mkproto
void containerBroadcast(int list_id,int id,int *member_ids,int member_count,NetLink *link);
void containerBroadcastAll(int list_id,int id);
void containerBroadcastMsg(int list_id,int msg_type,int senderID,int id,char *msg);
void handleSendMsg(Packet *pak);
// End mkproto
#endif
