#ifndef _DBPERF_H
#define _DBPERF_H


// Generated by mkproto
void flatToSql();
void sqlToFlat();
void dupContainer(unsigned runs);
void perfUpdate(unsigned runs);
void perfLoad(unsigned runs);
void modifyContainersAsync(unsigned containers);

void logStatCmdIn(int type,int size);
void logStatCmdOut(int type,int size);
void logSpecialCmd(int idx,int size);
void logStatPrint(int type);
void logStatGetContainer(int type,int size);
void logStatSetContainer(int type,int size);

enum
{
	DBPERF_CMDS_IN,
	DBPERF_NUMCMDS,
};

// End mkproto
#endif
