#ifndef _DOORS_H
#define _DOORS_H

#include "netio.h"

// Generated by mkproto
void doorStatusCb(DoorCon *container,char *buf);
void doorSetSpecialInfo(char *data,int *map_id,Vec3 pos);
void doorListSetSpecialInfo(DbList *list);
void sendDoorList(NetLink *link);
void sendDoorListToMapServers();
void handleNewClientDoors(Packet *pak,NetLink *link);
// End mkproto
#endif
