#ifndef _MAPXFER_H
#define _MAPXFER_H

#include "netio.h"
#include "container.h"

// Generated by mkproto
void sendLoginFailure(NetLink *link,int is_gameclient,int id,char *errmsg);
void sendLoginInfoToGameClient(EntCon *ent_con,int login_cookie);
int checkMapIDForOverrides(int map_id, EntCon *ent_con);
bool canStartStaticMap(int map_id, EntCon *ent_con);
int setNewMap(EntCon *ent_con,int map_id,NetLink *link,int is_gameclient,char *errmsg,int write_sql);
void finishSetNewMap(EntCon *ent_con, U32 container_id, U32 new_map_id, int is_map_xfer);
MapCon *startMapIfStatic(NetLink *link, EntCon* ent_con, int map_id, char *errmsg, const char* source);
MapCon *startInstancedMap(NetLink* link, EntCon* ent_con, char* mapinfo, char* errmsg, const char* source);
void dbForceLogout(int container_id,int reason);
// End mkproto
#endif
