#ifndef _STATUS_H
#define _STATUS_H

#include "container.h"
// Generated by mkproto
void entStatusCb(EntCon *container,char *buf);
void mapStatusCb(MapCon *container,char *buf);
void groupStatusCb(GroupCon *container,char *buf);
void handleWho(Packet *pak_in,NetLink *link);
void handleServerStatsUpdate(Packet *pak,int map_id);
void handleRequestSGEldestOn(Packet *pak_in, NetLink *link);
// End mkproto
#endif
