#ifndef _GROUPNETSEND_H
#define _GROUPNETSEND_H

typedef struct NetLink NetLink;
typedef struct GroupDef GroupDef;

extern int		world_id;
extern char	world_name[MAX_PATH];

// Generated by mkproto
void worldSendUpdate(NetLink *link,int full_update);
char* currentMapFile(void); // cleaned up world_name, can be used with ErrorFilenamef
void markDynamicDefChange(GroupDef *def);
void sendDynamicDefChanges(NetLink *link);
void clearDynamicDefChanges();

// End mkproto
#endif
