##############################################################################
# Name: Makefile
#

TOP     = ../..
HERE    = arda2/util

##############################################################################
# Define all local variables after the following line.
include $(TOP)/configure.mk

LIBNAME = ArdaUtil

SRCS_CPP = utlPoint.cpp utlRect.cpp utlTokenizer.cpp utlSize.cpp 	\
	   utlStringTable.cpp utlCmdLineParser.cpp utlStringHeap.cpp 	\
	   utlProperty.cpp

##############################################################################
# Define all local rules after the following line.
include $(CONFIG_DIR)/rules.mk

