#ifndef _CUTSCENE_H
#define _CUTSCENE_H


typedef struct CutSceneEvent
{	
	F32		time;
	char *	actor;
	char *	target;
	char *	action;
	char *	dialog;
	char *	position; //if actor is camera, tell it to move to this position
	char *	moveTo;	//	moveTo this position (lerp)
	F32		depthOfField;
	F32		moveToDepthOfField;
	int		over;
	char *  music;
	char *  soundfx;
	char *	leftText;
	char *	leftWatermark;
	char *	rightText;
	char *	rightWatermark;
	char *  leftObjective;
	char *  rightObjective;
	char *  leftReward;
	char *  rightReward;
} CutSceneEvent;

typedef struct CutSceneDef
{
	U32 flags;
	CutSceneEvent ** events;
	int initialized;
} CutSceneDef;

#define MAX_ROLE_STR_LEN 30

typedef struct CutSceneCastMember
{
	EntityRef entRef;
	char role[MAX_ROLE_STR_LEN];
} CutSceneCastMember;
extern TokenizerParseInfo ParseCutScene[];

#define MAX_ACTORS 100
#define MAX_CAMERA_MATS (50 - 1) //Equal to EG_MAX_ENCOUNTER_POSITIONS for now
typedef struct CutSceneParams
{
	int freezeServerAndMoveCameras;
	int flags;
	//You can give a cut scene def if you already it or else the name of one 
	char * cutSceneDefName; //(not yet implemented)
	const CutSceneDef * cutSceneDef;
	Mat4 cameraMats[MAX_CAMERA_MATS+1]; //since it's one based, and this is easier than subtracting elsewhere, plus zero in the script is the same as no command to move the camera
	int castCount;
	CutSceneCastMember cast[MAX_ACTORS]; //Give the ents their encounter actor name or do something else? Cheesed up static array since EntityRef is an int64 that won't work with Earray, fix someday to dynamic

} CutSceneParams;

// Generated by mkproto
void processCutScenes( F32 timestep );
int startCutScene( CutSceneParams * cutSceneParams );
void * cutSceneFromHandle( int handle );
void getCutSceneCameraPos( Vec3 vec );
void setEntityInCutScene( Entity * e );
Entity * getActorFromCutScene( int cutSceneHandle, char * actorName );
void cutSceneAddMapCamera( Mat4 mat, char * name );
int MadeCutsceneMoralChoice(int choice);
int CutscenePaused(void);
int cutscene_has_objective(const CutSceneDef ** csd, const char *objective);
// End mkproto
#endif