#ifndef _WIN_INIT_H
#define _WIN_INIT_H

#include "wininclude.h"
extern HINSTANCE glob_hinstance;
extern HWND	hwnd;

// Generated by mkproto
void winMakeCurrent();
void windowSize(int *width,int *height);
void windowClientSize(int *width, int *height);
int windowScaleY(int y);
void windowPosition(int *left,int *top);
void windowResize(int width,int height);
void windowInit(int *widthp,int *heightp,int fullscreen,int maximize);
void windowExit(int exitCode);
void windowExitDlg(void * data);
void windowUpdate();
void windowProcessMessages();
void windowShowError(char *str);
void windowsDialog( char *str );
void winMsgAlert(char *str);
int winMsgYesNo(char *str);
char *winGetFileName(char *fileMask,char *fileName,int save);
int winMaximized();
void winSetText(char *s);
void winCopyToClipboard(const char* s);
// End mkproto

#define TEXT_DIALOG_MAX_STRLEN 256 // callers must provide incoming buffer of this length or risk crash
bool winGetString(char* prompt, char* result); 
	// prompt for a string with a windows dialog box, returns false on cancel, fills in result with new value and returns true on ok

#endif
