#ifndef _GEO_H
#define _GEO_H

#include "GenericMesh.h"
#include "tree.h"

//mm
#define MAX_TRIIDX  10000
#define MAX_BUFFER  500000
#define MAX_TRISETS 1000


#define OBJECT_LIBRARY 0
#define PLAYER_LIBRARY 1
#define ANIMATION_FILE 2
#define SCALE_LIBRARY  3

#define NO_MERGE_NODES  0
#define MERGE_NODES		1

#define PROCESS_ALL_NODES	0
#define PROCESS_GEO_ONLY	1	//process only "GEO_" prefixed geometry parts
#define PROCESS_ANIM_ONLY	2	//ignore all "GEO_" prefixed parts
#define PROCESS_SCALEBONES_ONLY 3

#define DONT_POOL_VERTS				0
#define POOL_VERTS					1
#define POOL_VERTS_NOSTS			2
#define POOL_VERTS_NOSTS_NONORMS	3
#define POOL_VERTS_NONORMS			4

#define SHALLOW_COPY	0
#define DEEP_COPY		1

// Generated by mkproto
ModelLODInfo *getPlayerLibraryDefaultLODs(void);
void orientPos(Vec3 v);
void orientAngle(Vec4 v);
void geoAddFile(char *fname, char *geo_fname, int merge_nodes, int whattoditch, int do_unwrapping, int is_legacy);
void parseAnimNameFromFileName(char * fname, char * basename);
void nodeUvunwrap(Node *node);
// End mkproto
#endif
