#ifndef _TEXSORT_H
#define _TEXSORT_H

#include "stdtypes.h"
#include "tree.h"
//#include "../GetTex/texloaddesc.h"
#include "GenericMesh.h"

typedef struct TexInf TexInf;
typedef struct
{
	char	name[1000];
	TexInf	*ti;
} TexName;

extern TexName	tex_names[];
extern int		tex_name_count;

// Generated by mkproto
void texLoadAll(void);
void texNameClear(int addwhite);
int texNameAdd(char *name);
int cmpTex(int *a,int *b);
void reorderTriIdxsByTex(GMesh *mesh);
void texPrintUsage(void);
// End mkproto
#endif
